Release v2.12.6+rev1
balena-os/balena-iot2000 pull request #10
Opened 2018-05-02 04:22 UTC by floion

2018-05-02 08:32 UTC, spanceac approved these changes

2018-05-02 08:34 UTC, spanceac commented on CHANGELOG.md
> +# v2.12.6+rev1
Missing a bracket here

2018-05-02 08:35 UTC, spanceac commented on CHANGELOG.md
> +
Missing a bracket here

2018-05-02 08:36 UTC, spanceac requested changes

2018-05-02 08:36 UTC, spanceac commented on CHANGELOG.md
> +
Missing a bracket here

2018-05-02 10:06 UTC, floion commented on CHANGELOG.md
> +
Thanks. Fixed

2018-05-04 12:16 UTC, floion commented
Superseded by https://github.com/resin-os/resin-iot2000/pull/11

2018-05-04 12:16 UTC, closed without merging